---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sites/webelong.fr/public_html
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R .next/static $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R constants $DEPLOYPATH
    - /bin/cp -R out $DEPLOYPATH
    - /bin/cp -R utils $DEPLOYPATH
    - /bin/cp tailwind.config.ts $DEPLOYPATH
    - /bin/cp tsconfig.json $DEPLOYPATH
    - /bin/cp postcss.config.js $DEPLOYPATH
    - /bin/cp next.config.js $DEPLOYPATH
    - /bin/cp next-env.d.ts $DEPLOYPATH
